edition = "2023";

package zerum.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service TokenService {
  rpc GetToken(GetTokenRequest) returns (GetTokenResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/token/{id}"};
  }
  rpc ListTokens(ListTokensRequest) returns (ListTokensResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/token"};
  }
  rpc CreateToken(CreateTokenRequest) returns (CreateTokenResponse) {
    option (google.api.http) = {
      post: "/v1/token"
      body: "*"
    };
  }
  rpc UpdateToken(UpdateTokenRequest) returns (UpdateTokenResponse) {
    option (google.api.http) = {
      patch: "/v1/token"
      body: "*"
    };
  }
  rpc DeleteToken(DeleteTokenRequest) returns (DeleteTokenResponse) {
    option (google.api.http) = {delete: "/v1/token"};
  }
}

message Token {
  int64 id = 1;
  int64 user_id = 2;
  string name = 3;
  string description = 4;
  google.protobuf.Timestamp expires_at = 5;
  google.protobuf.Timestamp last_used_at = 6;
  google.protobuf.Timestamp created_at = 7;
}

message GetTokenRequest {
  int64 id = 1;
}
message GetTokenResponse {
  Token token = 1;
}

message ListTokensRequest {}
message ListTokensResponse {
  repeated Token tokens = 1;
}

message CreateTokenRequest {
  string name = 1 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100,
    (buf.validate.field).string.pattern = "^[a-z][a-z0-9_-]*$"
  ];
  string description = 2 [(buf.validate.field).string.max_len = 1000];
  google.protobuf.Timestamp expires_at = 3;
}
message CreateTokenResponse {
  Token token = 1;
  string secret = 2;
}

message UpdateTokenRequest {
  int64 id = 1;
  string name = 2 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100,
    (buf.validate.field).string.pattern = "^[a-z][a-z0-9_-]*$"
  ];
  string description = 3 [(buf.validate.field).string.max_len = 1000];
  google.protobuf.Timestamp expires_at = 4;
}
message UpdateTokenResponse {
  Token token = 1;
}

message DeleteTokenRequest {
  int64 id = 1;
}
message DeleteTokenResponse {}
