edition = "2023";

package zerum.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service APITokenService {
  rpc GetToken(GetTokenRequest) returns (GetTokenResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/token/{id}"};
  }
  rpc ListTokens(ListTokensRequest) returns (ListTokensResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/token"};
  }
  rpc CreateToken(CreateTokenRequest) returns (CreateTokenResponse) {
    option (google.api.http) = {
      post: "/v1/token"
      body: "*"
    };
  }
  rpc UpdateToken(UpdateTokenRequest) returns (UpdateTokenResponse) {
    option (google.api.http) = {
      patch: "/v1/token"
      body: "*"
    };
  }
  rpc DeleteToken(DeleteTokenRequest) returns (DeleteTokenResponse) {
    option (google.api.http) = {delete: "/v1/token"};
  }
}

message APIToken {
  string id = 1;
  string project_id = 2;
  string user_id = 3;
  string name = 4;
  google.protobuf.Timestamp expires_at = 5;
  google.protobuf.Timestamp last_used_at = 6;
  google.protobuf.Timestamp created_at = 7;
}

message GetTokenRequest {
  string project_id = 1 [(buf.validate.field).string.uuid = true];
  string id = 2 [(buf.validate.field).string.uuid = true];
}
message GetTokenResponse {
  APIToken token = 1;
}

message ListTokensRequest {
  string project_id = 1 [(buf.validate.field).string.uuid = true];
}
message ListTokensResponse {
  repeated APIToken tokens = 1;
}

message CreateTokenRequest {
  string project_id = 1 [(buf.validate.field).string.uuid = true];
  string name = 2 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100,
    (buf.validate.field).string.pattern = "^[a-z][a-z0-9_-]*$"
  ];
  google.protobuf.Timestamp expires_at = 3;
}
message CreateTokenResponse {
  APIToken token = 1;
  string secret = 2;
}

message UpdateTokenRequest {
  string project_id = 1 [(buf.validate.field).string.uuid = true];
  string id = 2 [(buf.validate.field).string.uuid = true];
  string name = 3 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100,
    (buf.validate.field).string.pattern = "^[a-z][a-z0-9_-]*$"
  ];
}
message UpdateTokenResponse {
  APIToken token = 1;
}

message DeleteTokenRequest {
  string project_id = 1 [(buf.validate.field).string.uuid = true];
  string id = 2 [(buf.validate.field).string.uuid = true];
}
message DeleteTokenResponse {}
