edition = "2023";

package zerum.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service SealService {
  rpc Seal(SealRequest) returns (SealResponse) {
    option (google.api.http) = {post: "/v1/seal"};
  }
  rpc Unseal(UnsealRequest) returns (UnsealResponse) {
    option (google.api.http) = {post: "/v1/unseal"};
  }
  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/seal"};
  }
}

message SealRequest {}
message SealResponse {}

message UnsealRequest {
  string unseal_key = 1 [(buf.validate.field).string.min_len = 1];
}
message UnsealResponse {}

message GetStatusRequest {}
message GetStatusResponse {
  bool sealed = 1;
  google.protobuf.Timestamp sealed_at = 2;
}
