syntax = "proto3";

package mantrae.v1;

service UtilService {
  rpc GetVersion(GetVersionRequest) returns (GetVersionResponse);
  rpc GetDynamicConfig(GetDynamicConfigRequest) returns (GetDynamicConfigResponse);
  rpc GetPublicIP(GetPublicIPRequest) returns (GetPublicIPResponse);
}

message GetVersionRequest {}
message GetVersionResponse {
  string version = 1;
}

message GetDynamicConfigRequest {
  int64 profile_id = 1;
}
message GetDynamicConfigResponse {
  string config = 1;
}

message GetPublicIPRequest {}
message GetPublicIPResponse {
  string ipv4 = 1;
  string ipv6 = 2;
}
