syntax = "proto3";

package mantrae.v1;

import "buf/validate/validate.proto";
import "mantrae/v1/agent.proto";
import "mantrae/v1/dns_provider.proto";
import "mantrae/v1/entry_point.proto";
import "mantrae/v1/middleware.proto";
import "mantrae/v1/profile.proto";
import "mantrae/v1/router.proto";
import "mantrae/v1/servers_transport.proto";
import "mantrae/v1/service.proto";
import "mantrae/v1/user.proto";

service UtilService {
  rpc GetVersion(GetVersionRequest) returns (GetVersionResponse);
  rpc GetDynamicConfig(GetDynamicConfigRequest) returns (GetDynamicConfigResponse);
  rpc GetPublicIP(GetPublicIPRequest) returns (GetPublicIPResponse);
}

message GetVersionRequest {}
message GetVersionResponse {
  string version = 1;
}

message GetDynamicConfigRequest {
  int64 profile_id = 1;
}
message GetDynamicConfigResponse {
  string config = 1;
}

message GetPublicIPRequest {}
message GetPublicIPResponse {
  string ipv4 = 1;
  string ipv6 = 2;
}
