edition = "2023";

package zyphor.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "zyphor/v1/options.proto";

service InvitationService {
  rpc GetInvitation(GetInvitationRequest) returns (GetInvitationResponse) {
    option (google.api.http) = {get: "/v1/invites/{token}"};
  }
  rpc CreateInvitation(CreateInvitationRequest) returns (CreateInvitationResponse) {
    option (google.api.http) = {post: "/v1/workspaces/{workspace_id}/invites/{expiry}"};
  }
  rpc AcceptInvitation(AcceptInvitationRequest) returns (AcceptInvitationResponse) {
    option (google.api.http) = {post: "/v1/invites/{token}"};
  }
}

message GetInvitationRequest {
  string token = 1 [
    (buf.validate.field).string.min_len = 1,
    (zyphor.v1.sensitive) = true
  ];
}
message GetInvitationResponse {
  string invited_by = 1;
  string workspace_name = 2;
}

message CreateInvitationRequest {
  string workspace_id = 1 [(buf.validate.field).string.uuid = true];
}
message CreateInvitationResponse {
  string link = 1 [(zyphor.v1.sensitive) = true];
  google.protobuf.Timestamp expires_at = 2;
}

message AcceptInvitationRequest {
  string token = 1 [
    (buf.validate.field).string.min_len = 1,
    (zyphor.v1.sensitive) = true
  ];
}
message AcceptInvitationResponse {
  string workspace_id = 1;
}
